### ISSUE TITLE
Whitelabel Error Page no ambiente de testes

### ISSUE THREAD

**Issue by vndmtrx** [lucasdiedrich/agatha#10]
Bom dia,

Aqui na instituição que trabalho, estamos passando por um problema referente à implantação do ambiente de testes e homologação do Agatha. Após carregar o sistema, é feita a tentativa de autenticação com os dados informados pelo Planejamento. No entanto, após o retorno da página do eCidadão, o sistema está retornando um erro 401 Unauthorized.

Havia visto em outros tópicos que o problema poderia estar relacionado ao fato de não ter a variável validacao-uri no arquivo application.yaml.

Nossa instalação não utiliza subfolders, tendo sido instalada na raiz do domínio teste.agatha.ifpr.edu.br, conforme fica exemplificado no print de tela anexo.

![captura de tela de 2019-01-22 09-49-27](https://user-images.githubusercontent.com/596651/51536504-f179cc00-1e32-11e9-9f22-434b614918f3.png)

Como também estou tentando usar no seu repositório e estou tendo o mesmo problema, achei pertinente reportar por aqui também (Issue original no [Portal do Software Público](https://softwarepublico.gov.br/gitlab/agatha/agatha/issues/21).

Ao entrar na página [Revogação de Acesso - Área do Cidadão](https://testeportal-ecidadao.estaleiro.serpro.gov.br/servicos-cidadao/area-cidadao/#/revogarAcesso) é possível ver que o AGATHA - IFPR está autorizado.

Em tempo, informo que segui os passos descritos nas Issues #1 e #7 para tentar solucionar as questões conforme mostrado nas mesmas.

Segue o conteúdo do application.yaml que estou atualmente usando para tentar a implantação do ambiente de testes:

```
ecidadao:
  client-id: XXXXXXXXXXXXXXXXXXXXXX
  client-secret: XXXXXXXXXXXXXXXXXXXXXX
  pre-established-redirect-uri: https://teste.agatha.ifpr.edu.br/gestaoriscos/api/login/openid
  sistema:
    dominio: teste.agatha.ifpr.edu.br
    url-pattern-protegido: /**
    redireciona-login-sucesso: https://teste.agatha.ifpr.edu.br
    redireciona-logout-sucesso:  https://teste.agatha.ifpr.edu.br
  use-current-uri: false
  scope: openid
  # URIS DO AMBIENTE DE TESTES
  access-token-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/token
  user-authorization-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/authorize
  validacao-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/jwk
```

Adicionalmente, como estou usando o docker-compose, este é o docker-compose.yaml atualmente em uso:

```
version: "3.6"
services:
  agathadb:
    image: postgres:11-alpine
    restart: always
    container_name: agathadb
    environment:
      POSTGRES_PASSWORD: grifpr
      POSTGRES_USER: gestaoriscos
      POSTGRES_DB: agatha
  agatha:
    image: lucasdiedrich/agatha
    restart: always
    container_name: agatha
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/rolim/build-agatha/config:/config"
      - "/etc/localtime:/etc/localtime"
    environment:
      DB_HOST: agathadb
      DB_PASSWORD: grifpr
      DB_USER: gestaoriscos
      DB_NAME: agatha
      DB_CHECK: 1
      CONF_CHECK: 0
      ECIDADAO_ENV: TESTE
      ECIDADAO_SERVER: teste.agatha.ifpr.edu.br
      ECIDADAO_ID: XXXXXXXXXXXXXXXXXXXXXXXXX
      ECIDADAO_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXX
      SIORG: 49103
    depends_on: 
     - agathadb
```

Atenciosamente,
